[package]
name = "haspid-lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ctor = "0.1"
axum = "0.5"
tokio = { version = "1.0", features = ["full"] }
twitch-irc = "4.0"
windows = { version = "0.36", features = [
	"alloc",
	"Win32_System_LibraryLoader"
] }